--DDL CRIAR BANCOS E TABELAS

--CRIAR UM BANCO
CREATE DATABASE Optus

--USAR O BANCO
USE Optus

CREATE TABLE Artistas
(
IdArtista INT PRIMARY KEY IDENTITY,
Nome VARCHAR(20) NOT NULL UNIQUE
)

CREATE TABLE Estilos
(
IdEstilo INT PRIMARY KEY IDENTITY,
Nome VARCHAR(20) NOT NULL
)

CREATE TABLE Usuarios
(
IdUsuarios INT PRIMARY KEY IDENTITY,
Nome VARCHAR(10) NOT NULL UNIQUE,
Email VARCHAR(30) NOT NULL UNIQUE,
Senha VARCHAR(10) NOT NULL,
Permissao VARCHAR(10) NOT NULL
)

CREATE TABLE Albuns
(
IdAlbum INT PRIMARY KEY IDENTITY,
IdArtista INT FOREIGN KEY REFERENCES Artistas(IdArtista) NOT NULL,
Titulo VARCHAR(10) NOT NULL UNIQUE,
DataLancamento DATE NOT NULL,
Localizacao VARCHAR(20) NOT NULL,
QtdMinutos VARCHAR(10) NOT NULL,
Ativo VARCHAR(10) NOT NULL
)

CREATE TABLE AlbunsEstilos
(
IdAlbunsEstilos INT PRIMARY KEY IDENTITY,
IdAlbum INT FOREIGN KEY REFERENCES Albuns(IdAlbum) NOT NULL,
IdEstilo INT FOREIGN KEY REFERENCES Estilos(IdEstilo) NOT NULL
)
SELECT * FROM Albuns
DROP TABLE AlbunsEstilos
DROP TABLE Usuarios
DROP TABLE Artistas
DROP TABLE Estilos

